### ISSUE TITLE
"python3.10": executable file not found in $PATH

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler-model-server#282]
### What happened?

```
Error: presteps pod: 2024/07/04 17:52:43 Error executing command: exec: "python3.10": executable file not found in $PATH
```

### What did you expect to happen?

running single-train: 
```
name: collect-idle
            image: $(params.MODEL_SERVER_IMAGE)
            args:
            - cmd/main.py
            - query
            - --data-path=$(workspaces.mnt.path)/data
            - --interval=$(params.IDLE_COLLECT_INTERVAL)
            - --thirdparty-metrics="$(params.THIRDPARTY_METRICS)"
            - --benchmark=idle
            - -o=idle
            - --id=$(params.MACHINE_ID)
            command: ["python3.10"]
```

### How can we reproduce it (as minimally and precisely as possible)?

Running default tekton pipeline after PR https://github.com/sustainable-computing-io/kepler-model-server/pull/280
Currently, model server image in the document is quay.io/sustainable_computing_io/kepler_model_server:v0.7.

### Anything else we need to know?

We just upgrade the version from 3.8 to 3.10 with the latest image. 
The command is using the upgraded version but the default image seems to still use 0.7.

### Kepler image tag

<details>
v0.7
</details>

### Deployment

- [ ] Model server
- [ ] Estimator
- [ ] Online trainer
- [X] Offline trainer
- [ ] Profiler

### Kepler model server image tag if deployed

<details>
v0.7
</details>

### Kepler estimator image tag if deployed

<details>

</details>

### Kepler online trainer image tag if deployed

<details>

</details>

### Kepler offline trainer image tag if deployed

<details>

</details>

### Kepler profiler image tag if deployed

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here
kind cluster


# provide kepler model server configmap if Kepler Model Server is deployed 
$ kubectl get configmap kepler-model-server-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>
